---
name: Log-Deep
version: 0.3.0
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
abstract: Deep Logging of information about a script state
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Clone: 0.29
  Data::Dump::Streamer: 2.08
  List::MoreUtils: 0
  Readonly: 1.03
  Term::ANSIColor: 0
  Time::HiRes: 1.9711
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
provides:
  Log::Deep:
    file: lib/Log/Deep.pm
    version: 0.3.0
  Log::Deep::File:
    file: lib/Log/Deep/File.pm
    version: 0.3.0
  Log::Deep::Line:
    file: lib/Log/Deep/Line.pm
    version: 0.3.0
  Log::Deep::Read:
    file: lib/Log/Deep/Read.pm
    version: 0.3.0
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
